### PR TITLE
tabs.py: Update to include swift driver

### PR DESCRIPTION
**Pull request by kay-kim**

### CODE REVIEW

**Comment by kay-kim** [comment]
@i80and -- if you could take a look and merge.

**Comment by i80and** [comment]
@kay-kim Sorry about the wait, Kay! I saw the email Friday evening, and it just slipped off my radar

**Comment by i80and** [comment]
@sophstad Do we need to add this to the frontend for next gen?

**Comment by kay-kim** [comment]
Heh - thanks @i80and!

**Pull request merged**
