### PR TITLE
DOCS-4507: Style Sheet: Make single-sentence steps more readable

### PR DESCRIPTION
**Pull request by atifazam**
https://jira.mongodb.org/browse/DOCS-4507?filter=-1

screen shot 2015-07-30 at 12 05 54 pm

### CODE REVIEW

**Comment by marcgurney** [comment]
We can probably remove the fonts from this commit since they were included in https://github.com/mongodb/docs-tools/pull/90

**Comment by kay-kim** [comment]
FYI -- step sequence are not always at H3 level.  Can be H4, some, even H5.

Also, I do see your intent of having the bottom border, but I don't think it works everywhere since in some places, the border makes it look like the final end of the sequence instead of a break between  steps.  I was wondering, if perhaps, instead of a border, could we make the break between steps smaller.  Our docs suffer from slight overabundance of whitespace between headings.

**Comment by atifazam** [comment]
Thanks for the feedback, Kay. I see what you're saying about the line breaks between steps. I removed them and decreased the spacing between steps.

screen shot 2015-08-04 at 11 18 21 am

**Comment by bgrabar** [comment]
As a related item, I think we no longer need to italicize the `guilabel`'s now that we've removed "all bold" from the steps (i.e., now that only the `guilabel` is bold and not the entire step).

**Comment by marcgurney** [comment]
@kay-kim @bgrabar Does this look good on your end? I'm not sure why the fonts are showing up in the diff since they should've been merged into master in https://github.com/mongodb/docs-tools/pull/90 but @atifazam or I can help with the merge process to make sure that we have the right files.

**Comment by kay-kim** [comment]
will finish testing on various docs sometime later this afternoon.
As for the fonts, it's because his origin is no longer tracking docs-tools master (since atif forked the repo).  He can update his origin to avoid this going forward, but for this pull, I can easily pick off the commits.

**Comment by bgrabar** [comment]
lgtm from style perspective, per discussion with @marcgurney, @atifazam.

**Comment by kay-kim** [comment]
one thing -- Atif, I'll swing by.

**Comment by kay-kim** [comment]
I've merged this on my local branch. I'm going to close this pull and ticket.  Thank you! 
Because this change affects various steps across different documents, I'll hold off on merging to master until we restructure the various pages themselves to take advantage of these changes.

**Pull request closed without merging**
