### PR TITLE
Updated feedback questions.

### PR DESCRIPTION
**Pull request by shannonbradshaw**
Added a few questions and tweaked the others.

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
Ping @i80and

**Comment by schmalliso** [comment]
I really like the edits, @shannonbradshaw - the questions are friendly, but also to the point 😺

**Comment by shannonbradshaw** [comment]
:-)

**Comment by i80and** [comment]
Great questions, Shannon! Only concern: the "reason" key appears in multiple places. Maybe we should make the last question "comments"?

**Comment by i80and** [comment]
Thank you, Shannon! Committed in c1e3d5b9a0c819052d15aaf88d5cf8fd2823f791 with the tweak I mentioned before.

**Pull request closed without merging**
