### PR TITLE
adds kafka-connector to dropdown

### PR DESCRIPTION
**Pull request by terakilobyte**
cc @jdestefano-mongo 

Adding kafka-connector to docs dropdown

Companion pr for docs-landing is https://github.com/mongodb/docs-landing/pull/34

### CODE REVIEW

**Comment by jdestefano-mongo** [comment]
Done this a handful of times and worked through it with Nathan. I think we're good but a review would be great, thanks!

**Comment by jdestefano-mongo** [comment]
@terakilobyte You still need to submit the PR with the copied navbar files to mongodb/docs-landing

**Comment by terakilobyte** [comment]
https://github.com/mongodb/docs-landing/pull/34

**Comment by i80and** [comment]
@terakilobyte Do you want this merged now, or are we holding off for something?

**Pull request merged**
